FROM jupyter/scipy-notebook:latest
MAINTAINER EBI Metagenomics Team

RUN $CONDA_DIR/bin/pip install jsonapi-client
# RUN $CONDA_DIR/bin/pip install "git+git://github.com/ola-t/jsonapi-client@master#egg=jsonapi-client"

# CMD ['start-singleuser.sh']